### ISSUE TITLE
Shift register implementation

### ISSUE THREAD

**Issue by scottjgibson** [VGottselig/ESP8266-RGB-Matrix-Panel#1]
Hi, I'm interested in your project but I am unclear about the shift register implementation in the arduino, do you have it working?

**Comment by VGottselig** [comment]
Yes. In README.md is a live Picture.
Do you have questions? I am waiting for "hardware" shift registers SN74HC595N

**Comment by VGottselig** [comment]
can be modified to Arduino Pin Change Interrupt
