### ISSUE TITLE
trying to understand code

### ISSUE THREAD

**Issue by joefly888** [VGottselig/ESP8266-RGB-Matrix-Panel#2]
Sorry for the naive question.  I am trying to simplify using the matrix display with only the esp8266.

I am not sure why the the arduino NANO is still used with your code?  Can this not be used solely with the esp8266?

And is this code stable enough to do graphics and animation?  any limitations such as refresh rate and memory?

**Comment by VGottselig** [comment]
Esp8266 does not have enough pins. 
50% CPU Load 
4096 Colors @ 30FPS
512 Colors @ 60FPS

I m working on port to ESP32. More pins, more ram, higher IO performance.

**Comment by sinks21** [comment]
I use it very well and well.
When can I view esp32 lib.

**Comment by joefly888** [comment]
thanks, for the response.

**Comment by SensorsIot** [comment]
I would also be interested in a ESP32 port!
