### ISSUE TITLE
I use it very well and well.

### ISSUE THREAD

**Issue by sinks21** [VGottselig/ESP8266-RGB-Matrix-Panel#3]
I use it very well and well.
 When can I view esp32 lib.?

**Comment by VGottselig** [comment]
Work in progress

**Comment by clowrey** [comment]
Are you working on a ESP32 version? I would be very interested in seeing the code, we are building displays to use as a PA system in a school with 2x 32x64 RGB for 32x128 - it is a non-profit enterprise. Right now the plan is to use raspberry pi 3, but if the ESP32 can work it would be much more cost effective.

**Comment by VGottselig** [comment]
Sorry, delayed because of other DIY projects.
This is next one now :)

**Comment by clowrey** [comment]
Awesome! Looking forward to trying it out sometime.

**Comment by VGottselig** [comment]
![image](https://user-images.githubusercontent.com/12281612/33566995-0e196dfe-d922-11e7-918e-c14c629c0d9a.png)
;)

**Comment by Nurgak** [comment]
I'm very much looking forward to the ESP32 version as well.

**Comment by VGottselig** [comment]
https://github.com/VGottselig/ESP32-RGB-Matrix-Display
